name: Deploy Cascade MCP

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

concurrency:
  group: deploy-${{ inputs.environment }}-${{ github.ref }}
  cancel-in-progress: false

env:
  PORT: 3000

jobs:
  Build-Server:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.vm_url}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate repo_env file
        run: |
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS }}" > repo_env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS }}" >> repo_env
          ####
          echo "VITE_COMMIT_SHA=${{ github.sha }}" >> repo_env
          echo "VITE_AUTH_SERVER_URL=${{ vars.VITE_AUTH_SERVER_URL }}" >> repo_env
          echo "VITE_JIRA_CLIENT_ID=${{ vars.VITE_JIRA_CLIENT_ID }}" >> repo_env
          echo "VITE_JIRA_SCOPE=${{ vars.VITE_JIRA_SCOPE }}" >> repo_env
          echo "VITE_JIRA_CALLBACK_URL=${{ vars.VITE_JIRA_CALLBACK_URL }}" >> repo_env
          echo "VITE_JIRA_API_URL=${{ vars.VITE_JIRA_API_URL }}" >> repo_env
          echo "VITE_STATUS_REPORTS_ENV=${{ inputs.environment }}" >> repo_env
          ####
          echo "JIRA_CLIENT_SECRET=${{ secrets.JIRA_CLIENT_SECRET }}" >> repo_env
          echo "FIGMA_CLIENT_ID=${{ vars.FIGMA_CLIENT_ID }}" >> repo_env
          echo "FIGMA_OAUTH_SCOPES=${{ vars.FIGMA_OAUTH_SCOPES }}" >> repo_env
          echo "FIGMA_CLIENT_SECRET=${{ secrets.FIGMA_CLIENT_SECRET }}" >> repo_env
          ####
          echo "GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }}" >> repo_env
          echo "GOOGLE_OAUTH_SCOPES=${{ vars.GOOGLE_OAUTH_SCOPES }}" >> repo_env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> repo_env
          ####
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> repo_env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> repo_env
          ####
          echo "PORT=${{ env.PORT }}" >> repo_env

      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          checkout: false
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS }}
          aws_default_region: us-east-1

          tf_state_bucket_destroy: true

          aws_r53_enable: true
          aws_r53_create_sub_cert: true
          aws_r53_sub_domain_name: ${{ inputs.environment == 'prod' && 'cascade' || format('cascade-{0}', inputs.environment) }}
          aws_r53_domain_name: bitovi.tools
          aws_elb_app_port: ${{ env.PORT }}

          docker_full_cleanup: true

          aws_ec2_instance_type: t3.medium
          aws_ec2_instance_root_vol_size: 16

          repo_env: repo_env

          aws_resource_identifier: ${{ inputs.environment == 'prod' && 'bitovi-jira-mcp-auth-bridge-prod' || '' }} 
          tf_state_bucket: ${{ inputs.environment == 'prod' && 'bitovi-jira-mcp-auth-bridge-prod-tf-state' || '' }}
